# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish

on: 
  #workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: "devci-demo-webapp"

   
jobs:
  publish: 
    runs-on: ubuntu-latest
    
    steps: 
    - uses : actions/checkout@v3
    
    - name : Setup  .NET
      uses: actions/setup-dotnet@v3
      with:
       dotnet-version: '6.0.x'
       
    - name: Restore
      run: dotnet restore ./demo-web-app/demo-web-app.sln
      
    - name: Build
      run: dotnet build ./demo-web-app/demo-web-app.sln --configuration Release --no-restore
      
    - name: Install EF Tool
      run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
          
    - name: Publish
      run: dotnet publish ./demo-web-app/demo-web-app.sln --configuration Release --no-build --output ./publish
      
    - name: Generate scripts
      run: dotnet ef migrations script --project ./demo-web-app/demo-web-app.csproj --output ./sql/sql-script.sql --idempotent --context AppDbContext
      
    - name: Azure SQL Deploy
      uses: Azure/sql-action@v2.2
      with:
        server-name: tcp:db-titan-demo.database.windows.net
        connection-string: ${{ secrets.CONNECTION_STRING }}
        sql-file: ./sql/sql-script.sql     
      
    # Deploy
    - name: Deploy to azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.PUBLISH_SECRET }}
        package: ./publish
#
